import { Product } from "@/types/product"

export const products: Product[] = [
  {
    id: 1,
    title: "ScreenWatch",
    price: 30,
    category: "wearables",
    image: "/products/1.png",
    description: "A sculpted smart wristpiece with a luminous edge-to-edge display.",
    rating: { rate: 4.5, count: 120 },
  },
  {
    id: 2,
    title: "SmartMouse",
    price: 80,
    category: "mouse",
    image: "/products/2.png",
    description: "A comfortable wireless mouse with precise tracking and ergonomic design.",
    rating: { rate: 4.8, count: 250 },
  },
    {
    id: 3,
    title: "Smart Laser",
    price: 20,
    category: "wearables",
    image: "/products/3.png",
    description: "A sleek and stylish wearable device with advanced health monitoring features.",
    rating: { rate: 4.5, count: 120 },
  },
    {
    id: 4,
    title: "Holo Laptop",
    price: 20,
    category: "laptop",
    image: "/products/4.png",
    description: "A portable laptop with a high-resolution display and powerful performance.",
    rating: { rate: 4.5, count: 120 },
  },
  {
    id: 5,
    title: "Holo Flexbook Elite",
    price: 150,
    category: "laptops",
    image: "/products/5.png",
    description: "A foldable next-generation laptop featuring a fluid adaptive display and premium materials.",
    rating: { rate: 4.9, count: 96 },
  },
  {
    id: 6,
    title: "Holo Prism Lounger",
    price: 3299,
    category: "furniture",
    image: "/products/6.png",
    description: "A statement lounge piece finished in iridescent metallic tones.",
    rating: { rate: 4.7, count: 74 },
  },
  {
    id: 7,
    title: "Holo Atlas Table",
    price: 4199,
    category: "smart-home",
    image: "/products/7.png",
    description: "An illuminated interactive table crafted as a centerpiece for entertainment, collaboration, and ambient digital living at the highest level.",
    rating: { rate: 4.8, count: 87 },
  },
  {
    id: 8,
    title: "Holo ClearPhone",
    price: 1399,
    category: "mobile",
    image: "/products/8.png",
    description: "A transparent concept-inspired smartphone with a clean floating interface.",
    rating: { rate: 4.4, count: 153 },
  },
  {
    id: 9,
    title: "Holo Nova Handset",
    price: 1199,
    category: "mobile",
    image: "/products/9.png",
    description: "A sleek performance handset with luminous detailing, precision contours, and a premium aesthetic.",
    rating: { rate: 4.6, count: 201 },
  },
  {
    id: 10,
    title: "Holo Sentinel Visor",
    price: 1599,
    category: "xr-devices",
    image: "/products/10.png",
    description: "A striking immersive visor designed with tactical sophistication, delivering a powerful visual experience in a sharply engineered form.",
    rating: { rate: 4.7, count: 111 },
  },
  {
    id: 11,
    title: "Holo Prism Tee",
    price: 189,
    category: "apparel",
    image: "/products/11.png",
    description: "A high-shine geometric statement tee that refracts light with dramatic effect, tailored for a bold and fashion-forward tech aesthetic.",
    rating: { rate: 4.5, count: 167 },
  },
  {
    id: 12,
    title: "Holo Cityscape Console",
    price: 5899,
    category: "smart-home",
    image: "/products/12.png",
    description: "A premium holographic display console built to transform planning, gaming, and collaboration into a stunning spatial experience.",
    rating: { rate: 4.9, count: 58 },
  },
  {
    id: 13,
    title: "Holo Glide Mouse",
    price: 229,
    category: "accessories",
    image: "/products/13.png",
    description: "A sculpted wireless mouse with a fluid silhouette and precision tracking, designed to elevate the feel of every interaction.",
    rating: { rate: 4.6, count: 143 },
  },
  {
    id: 14,
    title: "Holo Terminal One",
    price: 1799,
    category: "computing",
    image: "/products/14.png",
    description: "A retro-futurist desktop terminal that pairs nostalgic computing cues with holographic flair for an unmistakably collector-grade presence.",
    rating: { rate: 4.8, count: 91 },
  }
]